version: '3.8'
services:
  lebasee-front:
    image: sajadmrjl/lebasee:latest
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped